version: "3"

services:
  airflow:
    image: apache/airflow:2.7.1
  mongo:
    image: mongo
  neo:
    image: neo4j
  redis:
    image: redis:latest
  postgres:
    image: postgres:13
  notebook:
    build: notebook/  